"""add pts module

Revision ID: 45595fa3a100
Revises: e40e0e09a140
Create Date: 2026-03-15 22:53:01.245042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45595fa3a100'
down_revision = 'e40e0e09a140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('client_contact', sa.String(length=256), nullable=True),
    sa.Column('client_phone', sa.String(length=64), nullable=True),
    sa.Column('client_email', sa.String(length=128), nullable=True),
    sa.Column('systems', sa.String(length=512), nullable=True),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('commissioned_at', sa.DateTime(), nullable=True),
    sa.Column('next_to_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['object_categories.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('warranty_until', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['service_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['service_objects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('ip_or_url', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['service_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('engineer_id', sa.Integer(), nullable=True),
    sa.Column('next_to_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['service_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_records')
    op.drop_table('object_passwords')
    op.drop_table('object_files')
    op.drop_table('object_equipment')
    op.drop_table('service_objects')
    op.drop_table('object_categories')
    # ### end Alembic commands ###
